### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Better-Boy** [zsdonghao/text-to-image#16]
Traceback (most recent call last):
  File "train_txt2im.py", line 453, in <module>
    main_train()
  File "train_txt2im.py", line 61, in main_train
    v = rnn_embed(t_real_caption, is_train=True, reuse=False).outputs
  File "/home/abhilash/text-to-image/model.py", line 822, in rnn_embed
    name = 'rnn/dynamic')
  File "/home/abhilash/text-to-image/tensorlayer/layers.py", line 3928, in __init__
    self.cell = cell_fn(num_units=n_hidden, **cell_init_args)
TypeError: __init__() got an unexpected keyword argument 'reuse'

I'm getting this error, don't know why? Please help

**Comment by zsdonghao** [comment]
please report you TF and TL version

**Comment by Better-Boy** [comment]
```
>>> import tensorflow as tf
>>> tf.__version__
'1.1.0'
>>> import tensorlayer as tl
>>> tl.__version__
'1.4.3'

```

**Comment by Better-Boy** [comment]
Error Resolved.

**Comment by richardcann** [comment]
What solved this issue? I am getting the same error running with same versions of tensorflow and tensorlayer
